
import React from 'react';

export const PrivacyPolicy = () => (
  <div className="prose prose-slate max-w-none">
    <h1 className="text-3xl font-display font-black text-slate-900 mb-6">Privacy Policy</h1>
    <p className="text-slate-600 mb-4">Last Updated: May 20, 2024</p>
    <p className="mb-4">At SomnusAI, accessible from somnus-ai-analyzer.vercel.app, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by SomnusAI and how we use it.</p>
    
    <h2 className="text-xl font-bold mt-8 mb-4">Log Files</h2>
    <p className="mb-4">SomnusAI follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks.</p>

    <h2 className="text-xl font-bold mt-8 mb-4">Cookies and Web Beacons</h2>
    <p className="mb-4">Like any other website, SomnusAI uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.</p>

    <h2 className="text-xl font-bold mt-8 mb-4">Google DoubleClick DART Cookie</h2>
    <p className="mb-4">Google is one of a third-party vendor on our site. It also uses cookies, known as DART cookies, to serve ads to our site visitors based upon their visit to our site and other sites on the internet. However, visitors may choose to decline the use of DART cookies by visiting the Google ad and content network Privacy Policy at the following URL – <a href="https://policies.google.com/technologies/ads" className="text-indigo-600 underline">https://policies.google.com/technologies/ads</a></p>

    <h2 className="text-xl font-bold mt-8 mb-4">Our Advertising Partners</h2>
    <p className="mb-4">Some of advertisers on our site may use cookies and web beacons. Each of our advertising partners has their own Privacy Policy for their policies on user data.</p>
  </div>
);

export const TermsOfService = () => (
  <div className="prose prose-slate max-w-none">
    <h1 className="text-3xl font-display font-black text-slate-900 mb-6">Terms of Service</h1>
    <h2 className="text-xl font-bold mt-8 mb-4">1. Acceptance of Terms</h2>
    <p className="mb-4">By accessing this Website, you are agreeing to be bound by these Website Terms and Conditions of Use and agree that you are responsible for the agreement with any applicable local laws.</p>
    
    <h2 className="text-xl font-bold mt-8 mb-4">2. Medical Disclaimer</h2>
    <p className="mb-4 bg-amber-50 border border-amber-200 p-4 rounded-xl font-medium text-amber-800 italic">
      SomnusAI is an educational and self-assessment tool. The scores and recommendations provided are generated by Artificial Intelligence and are not a substitute for professional medical advice, diagnosis, or treatment. Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition.
    </p>

    <h2 className="text-xl font-bold mt-8 mb-4">3. Use License</h2>
    <p className="mb-4">Permission is granted to temporarily download one copy of the materials on SomnusAI's Website for personal, non-commercial transitory viewing only.</p>
  </div>
);

export const AboutUs = () => (
  <div className="prose prose-slate max-w-none">
    <h1 className="text-3xl font-display font-black text-slate-900 mb-6">About SomnusAI</h1>
    <p className="text-lg text-slate-700 mb-6 leading-relaxed">
      SomnusAI was founded by a team of technology enthusiasts and sleep researchers dedicated to making chronobiology accessible to everyone. We believe that understanding the nuances of your rest shouldn't require a sleep lab.
    </p>
    <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mt-10">
      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
        <h3 className="font-bold text-slate-900 mb-2">Our Mission</h3>
        <p className="text-slate-600">To provide high-quality, AI-driven sleep analysis that empowers individuals to take control of their restorative health through data-backed behavioral changes.</p>
      </div>
      <div className="bg-slate-50 p-6 rounded-2xl border border-slate-100">
        <h3 className="font-bold text-slate-900 mb-2">Our Technology</h3>
        <p className="text-slate-600">We utilize the Gemini Pro API to process complex environmental and habit data, mapping it against established sleep architecture patterns.</p>
      </div>
    </div>
  </div>
);

export const ContactUs = () => (
  <div className="prose prose-slate max-w-none">
    <h1 className="text-3xl font-display font-black text-slate-900 mb-6">Contact Us</h1>
    <p className="mb-8 text-slate-600">Have questions about our sleep assessment or need assistance? Our support team is here to help.</p>
    <div className="bg-white border border-slate-200 p-8 rounded-3xl shadow-sm max-w-lg">
      <div className="space-y-4">
        <div>
          <label className="block text-sm font-bold text-slate-700 mb-1">Email</label>
          <p className="text-indigo-600 font-medium">support@somnusai-demo.com</p>
        </div>
        <div>
          <label className="block text-sm font-bold text-slate-700 mb-1">Response Time</label>
          <p className="text-slate-600">We typically respond within 24-48 business hours.</p>
        </div>
      </div>
    </div>
  </div>
);
